# -*- coding: utf-8 -*-
"""System Capacity & Care Load Analytics for Unaccompanied Children.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZpSVcDLrgghCC792UKr0X0kUlj7srwUq
"""

import os

FILE_NAME = "HHS_Unaccompanied_Alien_Children_Program.csv"

# Automatically detect Colab or GitHub/local environment
if os.path.exists(f"/content/{FILE_NAME}"):
    FILE_PATH = f"/content/{FILE_NAME}"
else:
    FILE_PATH = FILE_NAME

print("Using dataset:", FILE_PATH)

# ============================================================
# SYSTEM CAPACITY & CARE LOAD ANALYTICS
# FOR UNACCOMPANIED CHILDREN (UAC)
#
# Compatible with:
# - Google Colab
# - Local Python
# - GitHub repository
# ============================================================


# ============================================================
# 1. IMPORT LIBRARIES
# ============================================================

import os
import pandas as pd
import numpy as np


# ============================================================
# 2. DATASET FILE DETECTION
# ============================================================

FILE_NAME = "HHS_Unaccompanied_Alien_Children_Program.csv"

COLAB_PATH = os.path.join("/content", FILE_NAME)
LOCAL_PATH = FILE_NAME

if os.path.exists(COLAB_PATH):
    FILE_PATH = COLAB_PATH

elif os.path.exists(LOCAL_PATH):
    FILE_PATH = LOCAL_PATH

else:
    raise FileNotFoundError(
        f"Dataset '{FILE_NAME}' was not found.\n"
        f"Checked Colab path: {COLAB_PATH}\n"
        f"Checked local/GitHub path: {LOCAL_PATH}"
    )

print("Dataset found successfully.")
print("Using file:", FILE_PATH)


# ============================================================
# 3. LOAD DATA
# ============================================================

df = pd.read_csv(FILE_PATH)

print("\nOriginal dataset shape:", df.shape)


# ============================================================
# 4. REMOVE COMPLETELY EMPTY ROWS
# ============================================================

df = df.dropna(how="all").copy()


# ============================================================
# 5. CLEAN COLUMN NAMES
# ============================================================

df.columns = df.columns.astype(str).str.strip()

print("\nColumns found in the dataset:")
for column in df.columns:
    print("-", column)


# ============================================================
# 6. RENAME DATASET COLUMNS
# ============================================================

column_mapping = {
    "Children apprehended and placed in CBP custody*": "Apprehended_CBP",
    "Children apprehended and placed in CBP custody": "Apprehended_CBP",
    "Children in CBP custody": "CBP_Custody",
    "Children transferred out of CBP custody": "Transferred_to_HHS",
    "Children in HHS Care": "HHS_Care",
    "Children discharged from HHS Care": "Discharged_HHS"
}

df = df.rename(columns=column_mapping)


# ============================================================
# 7. CHECK REQUIRED COLUMNS
# ============================================================

required_columns = [
    "Date",
    "Apprehended_CBP",
    "CBP_Custody",
    "Transferred_to_HHS",
    "HHS_Care",
    "Discharged_HHS"
]

missing_columns = []

for column in required_columns:
    if column not in df.columns:
        missing_columns.append(column)

if missing_columns:
    raise ValueError(
        "The following required columns are missing:\n"
        + "\n".join(missing_columns)
    )


# ============================================================
# 8. CONVERT DATE COLUMN
# ============================================================

df["Date"] = pd.to_datetime(
    df["Date"],
    errors="coerce"
)

df = df.dropna(subset=["Date"]).copy()


# ============================================================
# 9. CONVERT NUMERIC COLUMNS
# ============================================================

numeric_columns = [
    "Apprehended_CBP",
    "CBP_Custody",
    "Transferred_to_HHS",
    "HHS_Care",
    "Discharged_HHS"
]

for column in numeric_columns:

    df[column] = (
        df[column]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.strip()
    )

    df[column] = pd.to_numeric(
        df[column],
        errors="coerce"
    )

    df[column] = df[column].fillna(0)

    df[column] = df[column].clip(lower=0)


# ============================================================
# 10. SORT DATA BY DATE
# ============================================================

df = df.sort_values("Date").reset_index(drop=True)


# ============================================================
# 11. REMOVE DUPLICATE DATES
# ============================================================

df = df.drop_duplicates(
    subset=["Date"],
    keep="last"
).copy()


# ============================================================
# 12. DATA QUALITY VALIDATION
# ============================================================

df["Transfer_Anomaly"] = (
    df["Transferred_to_HHS"] > df["CBP_Custody"]
)

df["Discharge_Anomaly"] = (
    df["Discharged_HHS"] > df["HHS_Care"]
)

df["Reporting_Anomaly"] = (
    df["Transfer_Anomaly"] |
    df["Discharge_Anomaly"]
)


# ============================================================
# 13. TOTAL SYSTEM LOAD
# ============================================================

df["Total_System_Load"] = (
    df["CBP_Custody"] +
    df["HHS_Care"]
)


# ============================================================
# 14. NET DAILY INTAKE
# ============================================================

df["Net_Daily_Intake"] = (
    df["Transferred_to_HHS"] -
    df["Discharged_HHS"]
)


# ============================================================
# 15. CARE LOAD GROWTH RATE
# ============================================================

df["Care_Load_Growth_Rate"] = (
    df["Total_System_Load"]
    .pct_change()
    .replace([np.inf, -np.inf], np.nan)
    .fillna(0)
    * 100
)


# ============================================================
# 16. BACKLOG INDICATOR
# ============================================================

df["Backlog_Indicator"] = (
    df["Net_Daily_Intake"].cumsum()
)


# ============================================================
# 17. DISCHARGE OFFSET RATIO
# ============================================================

df["Discharge_Offset_Ratio"] = np.where(
    df["Transferred_to_HHS"] > 0,
    df["Discharged_HHS"] / df["Transferred_to_HHS"],
    0
)


# ============================================================
# 18. ROLLING AVERAGES
# ============================================================

df["System_Load_7D_Avg"] = (
    df["Total_System_Load"]
    .rolling(window=7, min_periods=1)
    .mean()
)

df["System_Load_14D_Avg"] = (
    df["Total_System_Load"]
    .rolling(window=14, min_periods=1)
    .mean()
)

df["Net_Intake_7D_Avg"] = (
    df["Net_Daily_Intake"]
    .rolling(window=7, min_periods=1)
    .mean()
)


# ============================================================
# 19. CARE LOAD VOLATILITY
# ============================================================

df["Daily_Load_Change"] = (
    df["Total_System_Load"]
    .pct_change()
    .replace([np.inf, -np.inf], np.nan)
)

df["Care_Load_Volatility"] = (
    df["Daily_Load_Change"]
    .rolling(window=7, min_periods=2)
    .std()
    .fillna(0)
    * 100
)


# ============================================================
# 20. HIGH LOAD THRESHOLD
# ============================================================

high_load_threshold = df["Total_System_Load"].quantile(0.75)

df["High_Load_Threshold"] = high_load_threshold

df["High_Load"] = (
    df["Total_System_Load"] >= high_load_threshold
)


# ============================================================
# 21. CAPACITY STRAIN
# ============================================================

df["Capacity_Strain"] = (
    df["High_Load"] &
    (df["Net_Daily_Intake"] > 0)
)


# ============================================================
# 22. CAPACITY RELIEF
# ============================================================

df["Capacity_Relief"] = (
    df["Net_Daily_Intake"] < 0
)


# ============================================================
# 23. STRAIN STREAK
# ============================================================

strain_streak = []
current_streak = 0

for value in df["Capacity_Strain"]:

    if bool(value):
        current_streak += 1
    else:
        current_streak = 0

    strain_streak.append(current_streak)

df["Strain_Streak"] = strain_streak


# ============================================================
# 24. TIME FEATURES
# ============================================================

df["Year"] = df["Date"].dt.year

df["Month"] = df["Date"].dt.month

df["Month_Name"] = df["Date"].dt.month_name()

df["Week"] = (
    df["Date"]
    .dt.isocalendar()
    .week
    .astype(int)
)


# ============================================================
# 25. KPI CALCULATIONS
# ============================================================

total_children_under_care = float(
    df["Total_System_Load"].iloc[-1]
)

average_net_intake = float(
    df["Net_Daily_Intake"].mean()
)

volatility_index = float(
    df["Care_Load_Volatility"].mean()
)

backlog_accumulation_rate = float(
    (df["Net_Daily_Intake"] > 0).mean() * 100
)

discharge_offset_ratio = float(
    df["Discharge_Offset_Ratio"].mean() * 100
)

high_load_rate = float(
    df["High_Load"].mean() * 100
)

capacity_strain_rate = float(
    df["Capacity_Strain"].mean() * 100
)

capacity_relief_rate = float(
    df["Capacity_Relief"].mean() * 100
)


# ============================================================
# 26. DISPLAY KPI RESULTS
# ============================================================

print("\n" + "=" * 65)
print("SYSTEM CAPACITY & CARE LOAD ANALYTICS")
print("UNACCOMPANIED CHILDREN (UAC)")
print("=" * 65)

print(f"\nTotal Children Under Care: {total_children_under_care:,.2f}")
print(f"Average Net Intake Pressure: {average_net_intake:,.2f}")
print(f"Care Load Volatility Index: {volatility_index:,.2f}")
print(f"Backlog Accumulation Rate: {backlog_accumulation_rate:.2f}%")
print(f"Discharge Offset Ratio: {discharge_offset_ratio:.2f}%")
print(f"High Load Rate: {high_load_rate:.2f}%")
print(f"Capacity Strain Rate: {capacity_strain_rate:.2f}%")
print(f"Capacity Relief Rate: {capacity_relief_rate:.2f}%")


# ============================================================
# 27. DATA QUALITY RESULTS
# ============================================================

print("\n" + "=" * 65)
print("DATA QUALITY RESULTS")
print("=" * 65)

print(
    "Transfer Anomalies:",
    int(df["Transfer_Anomaly"].sum())
)

print(
    "Discharge Anomalies:",
    int(df["Discharge_Anomaly"].sum())
)

print(
    "Total Reporting Anomalies:",
    int(df["Reporting_Anomaly"].sum())
)


# ============================================================
# 28. SAVE ANALYZED DATA
# ============================================================

OUTPUT_FILE = "UAC_Analyzed_Data.csv"

df.to_csv(
    OUTPUT_FILE,
    index=False
)

print("\n" + "=" * 65)
print("ANALYSIS COMPLETED SUCCESSFULLY")
print("=" * 65)

print("Output file created:", OUTPUT_FILE)

print("\nFirst 5 rows:")
print(df.head())

print("Dataset Shape:", df.shape)

print("\nDate Range:")
print("Start:", df["Date"].min())
print("End:", df["Date"].max())

print("\nMissing Values:")
print(df.isnull().sum())

print("\nData Types:")
print(df.dtypes)

df.head()

import matplotlib.pyplot as plt

plt.figure(figsize=(14, 6))

plt.plot(
    df["Date"],
    df["CBP_Custody"],
    label="CBP Custody"
)

plt.plot(
    df["Date"],
    df["HHS_Care"],
    label="HHS Care"
)

plt.plot(
    df["Date"],
    df["Total_System_Load"],
    label="Total System Load"
)

plt.title("CBP vs HHS Care Load Over Time")

plt.xlabel("Date")

plt.ylabel("Number of Children")

plt.legend()

plt.grid(True)

plt.tight_layout()

plt.show()

plt.figure(figsize=(14, 6))

plt.plot(
    df["Date"],
    df["Total_System_Load"]
)

plt.title("Total System Capacity Load Over Time")

plt.xlabel("Date")

plt.ylabel("Total Children Under Care")

plt.grid(True)

plt.tight_layout()

plt.show()

plt.figure(figsize=(14, 6))

plt.plot(
    df["Date"],
    df["Net_Daily_Intake"],
    label="Net Daily Intake"
)

plt.axhline(
    y=0,
    linestyle="--"
)

plt.title("Net Daily Intake Pressure")

plt.xlabel("Date")

plt.ylabel("Transfers - Discharges")

plt.legend()

plt.grid(True)

plt.tight_layout()

plt.show()

plt.figure(figsize=(14, 6))

plt.plot(
    df["Date"],
    df["Backlog_Indicator"]
)

plt.title("Backlog Accumulation Trend")

plt.xlabel("Date")

plt.ylabel("Cumulative Net Intake")

plt.grid(True)

plt.tight_layout()

plt.show()

plt.figure(figsize=(14, 6))

plt.plot(
    df["Date"],
    df["Total_System_Load"],
    label="Daily Load",
    alpha=0.5
)

plt.plot(
    df["Date"],
    df["System_Load_7D_Avg"],
    label="7-Day Average"
)

plt.plot(
    df["Date"],
    df["System_Load_14D_Avg"],
    label="14-Day Average"
)

plt.title("System Load Rolling Average Analysis")

plt.xlabel("Date")

plt.ylabel("Total System Load")

plt.legend()

plt.grid(True)

plt.tight_layout()

plt.show()

monthly_data = (
    df
    .set_index("Date")
    .resample("ME")["Total_System_Load"]
    .mean()
)

plt.figure(figsize=(14, 6))

plt.plot(
    monthly_data.index,
    monthly_data.values
)

plt.title("Monthly Average System Load")

plt.xlabel("Month")

plt.ylabel("Average Children Under Care")

plt.grid(True)

plt.tight_layout()

plt.show()

plt.figure(figsize=(14, 6))

plt.plot(
    df["Date"],
    df["Total_System_Load"],
    label="Total System Load"
)

strain_data = df[
    df["Capacity_Strain"] == True
]

plt.scatter(
    strain_data["Date"],
    strain_data["Total_System_Load"],
    label="Capacity Strain"
)

plt.title("Capacity Strain Periods")

plt.xlabel("Date")

plt.ylabel("Total System Load")

plt.legend()

plt.grid(True)

plt.tight_layout()

plt.show()

kpi_summary = pd.DataFrame({
    "KPI": [
        "Total Children Under Care",
        "Average Net Intake Pressure",
        "Care Load Volatility Index",
        "Backlog Accumulation Rate (%)",
        "Discharge Offset Ratio (%)",
        "High Load Rate (%)",
        "Capacity Strain Rate (%)",
        "Capacity Relief Rate (%)"
    ],
    "Value": [
        total_children_under_care,
        average_net_intake,
        volatility_index,
        backlog_accumulation_rate,
        discharge_offset_ratio,
        high_load_rate,
        capacity_strain_rate,
        capacity_relief_rate
    ]
})

kpi_summary

kpi_summary.to_csv(
    "UAC_KPI_Summary.csv",
    index=False
)

print("KPI Summary saved successfully!")



